Vagrant.configure(2) do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.define "donghankS" do |control|
        control.vm.hostname = "donghankS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "virtualbox" do |v|
          v.customize [
            "modifyvm", :id, 
            "--name", "donghankS",
            "--cpus", "1",
            "--memory", "512"
          ]
        end
        control.vm.provision "shell", path: "setup.sh", args: ["server"]
    end

    config.vm.define "donghankSW" do |control|
      control.vm.hostname = "donghankSW"
      control.vm.network "private_network", ip: "192.168.56.111"
      control.vm.provider "virtualbox" do |v|
        v.customize [
          "modifyvm", :id,
          "--name", "donghankSW",
          "--cpus", "1",
          "--memory", "512"
        ]
      end
      control.vm.provision "shell", path: "setup.sh", args: ["server-worker"]
    end
  end