Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/jammy64"

    config.vm.define "donghankS" do |control|
        control.vm.hostname = "donghankS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "virtualbox" do |v|
          v.customize [
            "modifyvm", :id, 
            "--name", "donghankS",
            "--cpus", "1",
            "--memory", "1024"
          ]
        end
        control.vm.provision "shell", path: "scripts/setup.sh"
    end
  end